FROM resin/%%RESIN_MACHINE_NAME%%-debian

WORKDIR /usr/src/app
ENV INITSYSTEM on

RUN apt-get -q update && apt-get install -yq --no-install-recommends \
      build-essential curl file \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN curl -sSf https://static.rust-lang.org/rustup.sh | sh

COPY . ./

RUN cargo build

CMD ./target/debug/blinktdemo
