FROM resin/%%RESIN_MACHINE_NAME%%-alpine

WORKDIR /usr/src/app
ENV INITSYSTEM on

RUN apk add --no-cache \
      build-base curl file sudo

RUN adduser -S resin
USER resin

RUN curl -sSf https://static.rust-lang.org/rustup.sh | sh

COPY . ./

RUN cargo build

CMD ./target/debug/blinktdemo
